# Generated by Django 4.1.2 on 2022-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
