# Generated by Django 4.1.2 on 2022-11-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_experience_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
