# Generated by Django 4.1.2 on 2022-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_experience_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(choices=[('FT', 'Full Time'), ('IN', 'Internship')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
